name: divvun-manager (windows)

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Nerdbank.GitVersioning needs a full clone
          fetch-depth: 0
      - uses: actions/checkout@v2
        with:
          repository: divvun/oneclick-bundler
          path: oneclick-bundler
      - name: Setup Divvun CI
        uses: divvun/actions/setup@master
        with:
          key: ${{ secrets.DIVVUN_KEY }}
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        with:
          nuget-version: '5.x'
      - name: Nerdbank.GitVersioning
        uses: dotnet/nbgv@master
        with:
          setCommonVars: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rust-src
          target: i686-pc-windows-msvc
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: xargo
      - name: Get version
        id: version
        uses: divvun/actions/version@master
        with:
          csharp: true
          stable-channel: beta
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Acquire build dependencies
        uses: divvun/actions/pahkat/init@master
        with:
          repo: https://pahkat.uit.no/devtools/
          channel: nightly
          packages: pahkat-uploader, pahkat-windows-cli, dotnet5-webinst, kbdi
      - name: Move dotnet5-webinst to appropriate places
        run: |
          ls -R $env:RUNNER_TEMP\pahkat-prefix\pkg\dotnet5-webinst
          cp $env:RUNNER_TEMP\pahkat-prefix\pkg\dotnet5-webinst\bin\dotnet5-webinst.exe $env:RUNNER_WORKSPACE\divvun-manager-windows\
          cp $env:RUNNER_TEMP\pahkat-prefix\pkg\dotnet5-webinst\bin\dotnet5-webinst.exe $env:RUNNER_WORKSPACE\divvun-manager-windows\oneclick-bundler\
          cp $env:RUNNER_TEMP\pahkat-prefix\pkg\kbdi\bin\kbdi.exe $env:RUNNER_WORKSPACE\divvun-manager-windows\oneclick-bundler\
          cp $env:RUNNER_TEMP\pahkat-prefix\pkg\kbdi\bin\kbdi-x64.exe $env:RUNNER_WORKSPACE\divvun-manager-windows\oneclick-bundler\
      - name: Acquire Pahkat Service installer (nightly)
        if: ${{ steps.version.outputs.channel == 'nightly' }}
        run: |
          mkdir ./pahkat-config
          echo "[""https://pahkat.uit.no/divvun-installer/""]`nchannel = ""nightly""" > ./pahkat-config/repos.toml
          pahkat-windows download https://pahkat.uit.no/divvun-installer/packages/pahkat-service --output ./pahkat-service -c ./pahkat-config
          mv ./pahkat-service/* ./pahkat-service-setup.exe
      - name: Acquire Pahkat Service installer (stable)
        if: ${{ steps.version.outputs.channel != 'nightly' }}
        run: |
          mkdir ./pahkat-config
          echo "[""https://pahkat.uit.no/divvun-installer/""]`nchannel = ""beta""" > ./pahkat-config/repos.toml
          pahkat-windows download https://pahkat.uit.no/divvun-installer/packages/pahkat-service --output ./pahkat-service -c ./pahkat-config
          mv ./pahkat-service/* ./pahkat-service-setup.exe
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          nuget restore "Divvun.Installer.sln"
          MSBuild.exe "Divvun.Installer.sln" /p:Configuration=Release /p:Platform=x86 /m  || exit /b !ERRORLEVEL!
      - name: Package OneClick
        shell: cmd
        run: |
          dotnet publish .\Divvun.Installer.OneClick\Divvun.Installer.OneClick.csproj /p:Platform=x86 /p:Configuration=Release
          cp Divvun.Installer.OneClick/publish/Divvun.Installer.OneClick.exe oneclick-bundler\
          cd oneclick-bundler
          cargo xtask
      - name: Sign code (Divvun Manager exe)
        uses: divvun/actions/codesign@master
        with:
          path: Divvun.Installer/bin/x86/Release/net5.0-windows10.0.18362.0/win-x86/DivvunManager.exe
      - name: Sign code (Divvun Installer OneClick exe)
        uses: divvun/actions/codesign@master
        with:
          path: oneclick-bundler/target/dist/Divvun.Installer.OneClick.exe
      - name: Sign code (Pahkat SDK DLL)
        uses: divvun/actions/codesign@master
        with:
          path: Divvun.Installer/bin/x86/Release/net5.0-windows10.0.18362.0/win-x86/Pahkat.Sdk.dll 
      - name: Sign code (Pahkat SDK RPC DLL)
        uses: divvun/actions/codesign@master
        with:
          path: Divvun.Installer/bin/x86/Release/net5.0-windows10.0.18362.0/win-x86/Pahkat.Sdk.Rpc.dll
      - name: Create installer
        id: installer
        uses: divvun/actions/inno-setup@master
        with:
          path: setup.iss
          defines: Version=${{ steps.version.outputs.version }}
      - name: Deploy (Divvun Manager)
        uses: divvun/actions/deploy@master
        with:
          # The id must be this, for legacy reasons.
          package-id: divvun-installer
          platform: windows
          version: ${{ steps.version.outputs.version }}
          payload-path: ${{ steps.installer.outputs.installer-path }}
          repo: https://pahkat.thetc.se/divvun-installer/
          channel: ${{ steps.version.outputs.channel }}
          windows-kind: inno
          windows-product-code: "{4CF2F367-82A8-5E60-8334-34619CBA8347}_is1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy (OneClick)
        uses: divvun/actions/deploy@master
        with:
          package-id: divvun-installer-oneclick
          platform: windows
          arch: i686
          # This product code isn't actually used but is a mandatory field.
          windows-product-code: "divvun-manager-oneclick"
          version: ${{ steps.version.outputs.version }}
          payload-path: oneclick-bundler/target/dist/Divvun.Installer.OneClick.exe
          repo: https://pahkat.thetc.se/divvun-installer/
          channel: ${{ steps.version.outputs.channel }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}